image: java:8-jdk
stages:
  - build
  - test

before_script:
  - chmod 777 ./gradlew

build:
  stage: build
  script:
    - ./gradlew assemble

  artifacts:
    paths:
      - build/libs/*.jar

tests:
  stage: test
  script:
    - ./gradlew test

  artifacts:
    paths:
      - build/jacocoHtml/**
      
